[workspace]
resolver = "3"
members = [
    "bevy-mod-indigauge", 
    "indigauge-core",
    "indigauge-types"
]

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
