max_width = 120
fn_call_width = 120
doc_comment_code_block_width = 120
format_code_in_doc_comments = true
imports_granularity = 'Crate'
normalize_comments = true
edition = "2024"
format_strings = true
match_block_trailing_comma = true
merge_derives = false
reorder_impl_items = true
tab_spaces = 2
use_field_init_shorthand = true