on:
  push:
    branches: [main]
    paths-ignore:
      - "**.md"
      - "static/**"
  pull_request:
    branches: [main]
    paths-ignore:
      - "**.md"
      - "static/**"

name: Continuous Integration

env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  check:
    name: Run cargo check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: install dependencies
        run: |
          sudo apt-get update; sudo apt-get install pkg-config libx11-dev libasound2-dev libudev-dev libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev

      - name: Run cargo check
        run: cargo check --all-targets

      - name: Run cargo check headless
        run: cargo check --all-targets --no-default-features

  docs:
    name: Run cargo doc
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: install dependencies
        run: |
          sudo apt-get update; sudo apt-get install pkg-config libx11-dev libasound2-dev libudev-dev libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev

      - name: Run cargo doc
        run: cargo doc --no-deps --all-features

  clippy_check:
    name: Run clippy check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: install dependencies
        run: |
          sudo apt-get update; sudo apt-get install pkg-config libx11-dev libasound2-dev libudev-dev libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev

      - name: Run Clippy
        run: cargo clippy --all-targets --all-features

  build_examples:
    name: Build examples
    runs-on: ubuntu-latest
    needs: [check, docs, clippy_check, test]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: install dependencies
        run: |
          sudo apt-get update; sudo apt-get install pkg-config libx11-dev libasound2-dev libudev-dev libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev

      - name: Build examples
        run: cargo build --examples

  test:
    name: Tests
    strategy:
      # Tests are most likely to have OS-specific behavior
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    runs-on: ${{ matrix.os }}
    needs: [check, docs, clippy_check]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install Linux dependencies
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: sudo apt-get update; sudo apt-get install pkg-config libx11-dev libasound2-dev libudev-dev libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev

      - name: Run cargo test
        run: cargo test --all-features
